# Generated by Django 2.2.5 on 2019-09-22 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(db_index=True, max_length=50, verbose_name='Имя')),
                ('surname', models.TextField(db_index=True, max_length=50, verbose_name='Фамилия')),
                ('date_birth', models.DateField(blank=True, max_length=25, verbose_name='Дата рождения')),
                ('number', models.CharField(max_length=15, verbose_name='Номер телефона')),
                ('e_mail', models.EmailField(db_index=True, max_length=250, verbose_name='E-Mail')),
                ('course_id', models.CharField(blank=True, db_index=True, max_length=250, verbose_name='Группа')),
            ],
        ),
    ]
